### ISSUE TITLE
Opening the trajectory or metadata operations??

### ISSUE THREAD

**Issue by mkhoshle** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#10]
@orbeckst I believe the tag for time comparison on different parts of the calculations per MPI rank in fig 1d and other similar figures should change. Opening the trajectory might not be the correct name. Because it is not necessarily opening. It contains mostly metadata. Maybe I should call this Meta-data?

**Comment by orbeckst** [comment]
I would leave it because even though at the underlying OS level this might indeed do mostly metadata operations, at the program (user view) level in the code it refers to the opening of the trajectory. 

We named the other components from the user perspective, too, so I think this is all consistent. 

If you want to you can add a sentence to the manuscript to clarify if you think it helps. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by mkhoshle** [comment]
Ok, then I will keep it the way it is.
