### ISSUE TITLE
does GA use MPI?

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#32]
I *think* our GA implementation (5.6.1) uses MPI at the lowest level: from http://hpc.pnl.gov/globalarrays/

> Starting with GA v5.4, ARMCI has been deprecated and replaced with Communication runtime for Extreme Scale (ComEx). GA uses ComEx to abstract inter-node communication operations. The default ComEx ports use MPI --- which makes GA and ComEx portable for high-end systems. Most ComEx implementations use on-node shared memory for faster intra-node communication. 

This should be made clear in the section on GA. The appropriate reference is
1. J. Daily, A. Vishnu, B. Palmer, H. van Dam, and D. Kerbyson. On the suitability of MPI as a PGAS runtime. In 2014 21st International Conference on High Performance Computing (HiPC), pages 1–10, Dec 2014. http://dx.doi.org/10.1109/HiPC.2014.7116712

**Comment by mkhoshle** [comment]
Yes, GA is compatible with MPI. Goal of GA is to free the programmer from the low-level management of communication and allow them to deal with their problems at the level at which they were originally formulated. In MPI in order to get good performance sometimes, we need to have some considerations of the computer architecture and memory hierarchy. However, global array makes it easier for people who are not expert in CS (like MD community) but at the same time want to get good performance. Again, I believe we do not really need to go into the details of this. At the same time, the compatibility of GA with MPI enables the programmer to take advantage of the existing MPI software/libraries when available and appropriate.
